#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║        🐷 OINKONOMICS - 30K NFTs Configuration 🐷            ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 DISTRIBUTION DES 30,000 NFTs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Tier    │  Range NFT        │  Quantité  │  Layers  │ Status"
echo "  ────────┼───────────────────┼────────────┼──────────┼────────"
echo "  POOR    │  0 → 9,999        │   10,000   │    6     │   ✅"
echo "  MID     │  10,000 → 19,999  │   10,000   │    8     │   ✅"
echo "  RICH    │  20,000 → 29,999  │   10,000   │    8     │   ✅"
echo "  ────────┼───────────────────┼────────────┼──────────┼────────"
echo "  TOTAL   │  0 → 29,999       │   30,000   │    -     │   ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 ASSETS DISPONIBLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  POOR (6 layers):"
echo "    • Background: 10 variations"
echo "    • Skin:        4 variations"
echo "    • Outfit:     10 variations"
echo "    • Eyes:        8 variations"
echo "    • Mouth:       8 variations"
echo "    • Headtop:    16 variations"
echo "    → Combinaisons possibles: 409,600 ✅"
echo ""
echo "  MID (8 layers):"
echo "    • Background: 10 variations"
echo "    • Skin:        4 variations"
echo "    • Outfit:      8 variations"
echo "    • Eyes:        8 variations"
echo "    • Nose:        8 variations"
echo "    • Ears:        8 variations"
echo "    • Mouth:      12 variations"
echo "    • Headtop:    15 variations"
echo "    → Combinaisons possibles: 29,491,200 ✅"
echo ""
echo "  RICH (8 layers):"
echo "    • Background: 10 variations"
echo "    • Skin:        5 variations"
echo "    • Outfit:     10 variations"
echo "    • Eyes:       10 variations"
echo "    • Nose:        8 variations"
echo "    • Ears:       12 variations"
echo "    • Mouth:      12 variations"
echo "    • Headtop:    15 variations"
echo "    → Combinaisons possibles: 86,400,000 ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚙️  COMMANDES DISPONIBLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Test rapide (30 NFTs):"
echo "    ./test-generation.sh"
echo ""
echo "  Génération complète (30,000 NFTs):"
echo "    npm run build"
echo ""
echo "  Génération par tier:"
echo "    TIER=POOR npm run build          # 10K POOR"
echo "    TIER=MID APPEND_MODE=true npm run build    # 10K MID"
echo "    TIER=RICH APPEND_MODE=true npm run build   # 10K RICH"
echo ""
echo "  Génération limitée (test):"
echo "    TEST_TIER_SIZE=100 npm run build # 100 par tier"
echo ""
echo "  Préparation pour déploiement:"
echo "    npm run prepare-sugar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 MÉTADONNÉES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Nom: Oinkonomics"
echo "  Symbole: OINK"
echo "  Royalties: 5%"
echo "  Format: 1000x1000px PNG"
echo "  Blockchain: Solana"
echo "  Prix mint: 0.1 SOL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏱️  ESTIMATIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Génération 30K NFTs:  ~1h30-2h"
echo "  Préparation Sugar:    ~5-10 min"
echo "  Upload Arweave:       ~30-60 min"
echo "  Déploiement total:    ~2h30-3h30"
echo ""
echo "  Espace disque requis: ~10-15 GB"
echo "  Coût mainnet estimé:  ~5-7 SOL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ CONFIGURATION VALIDÉE - PRÊT À GÉNÉRER!"
echo ""
echo "🚀 Pour commencer:"
echo "   1. Test rapide:      ./test-generation.sh"
echo "   2. Génération full:  npm run build"
echo "   3. Voir la doc:      cat CONFIG_30K_READY.md"
echo ""
