#!/usr/bin/env bash
set -euo pipefail

# Detect repository root
if git rev-parse --show-toplevel >/dev/null 2>&1; then
  PROJECT_ROOT="$(git rev-parse --show-toplevel)"
else
  PROJECT_ROOT="$(pwd)"
fi

# Defaults (override with env vars if required)
CACHE_PATH="${CACHE_PATH:-$PROJECT_ROOT/cache.json}"
KEYPAIR_PATH="${KEYPAIR_PATH:-$HOME/.config/solana/id.json}"
RPC_URL="${RPC_URL:-https://api.devnet.solana.com}"

# jq dependency
if ! command -v jq >/dev/null 2>&1; then
  echo "Error: 'jq' is required (e.g. sudo apt-get install jq)"; exit 1
fi

# Ensure cache.json exists
if [ ! -f "$CACHE_PATH" ]; then
  echo "Error: cache not found at $CACHE_PATH"; exit 1
fi

# Extract the candyMachineCreator PDA
CMA="$(jq -r '.program.candyMachineCreator // empty' "$CACHE_PATH")"
if [ -z "$CMA" ] || [ "$CMA" = "null" ]; then
  echo "Error: .program.candyMachineCreator missing in $CACHE_PATH"; exit 1
fi

ENV_FILE="${1:-.env}"

# Backup existing env if needed
if [ -f "$ENV_FILE" ]; then
  BKP="${ENV_FILE}.backup.$(date +%s)"
  cp -a "$ENV_FILE" "$BKP"
  echo "Created backup: $BKP"
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/gen-env.sh
# Load with:  set -a; source $ENV_FILE; set +a

# --- Project & paths ---
PROJECT_ROOT=$PROJECT_ROOT
ENV_PATH=
CONFIG_JSON_PATH=$PROJECT_ROOT/config.json
GUARD_CONFIG_JSON_PATH=$PROJECT_ROOT/guard.config.json
CONFIG_LOCAL_JSON_PATH=$PROJECT_ROOT/config.local.json

# --- Solana / Umi ---
RPC_URL=$RPC_URL
KEYPAIR_PATH=$KEYPAIR_PATH
CACHE_PATH=$CACHE_PATH
GUARD_CONFIG_PATH=$PROJECT_ROOT/guard.config.json
GUARD_LABEL=default
# IMPORTANT: must be the candyMachineCreator PDA (auto-filled)
COLLECTION_UPDATE_AUTHORITY=$CMA
COMPUTE_UNITS=400000
PRIORITY_MICROLAMPORTS=0

# --- Collection metadata / Candy Machine ---
COLLECTION_NAME_PREFIX=Name of your NFT
COLLECTION_DESCRIPTION=Project tagline and value proposition
COLLECTION_BASE_URI=ipfs://NewUriToReplace
COLLECTION_SIZE=10
COLLECTION_SYMBOL=OINCO
COLLECTION_EXTERNAL_URL=https://www.your-site.com
COLLECTION_SELLER_FEE_BPS=1000
COLLECTION_NETWORK=sol
CREATOR_ADDRESS=5zHBXzhaqKXJRMd7KkuWsb4s8zPyakKdijr9E3jgyG8Z
CREATOR_SHARE=100
COLLECTION_CREATORS_JSON=
TOKEN_STANDARD=nft
IS_MUTABLE=true
IS_SEQUENTIAL=false
UPLOAD_METHOD=pinata
RULE_SET=null
MAX_EDITION_SUPPLY=null
HIDDEN_SETTINGS=null
AWS_CONFIG=null
SDRIVE_API_KEY=
NFT_STORAGE_AUTH_TOKEN=
SHDW_STORAGE_ACCOUNT=

# --- Pinata (fill in when using Pinata uploads) ---
PINATA_JWT=
PINATA_API_GATEWAY=https://api.pinata.cloud
PINATA_CONTENT_GATEWAY=https://gateway.pinata.cloud
PINATA_PARALLEL_LIMIT=100

# --- Candy Guard (solPayment) ---
SOL_PAYMENT_VALUE=0.01
SOL_PAYMENT_DESTINATION=5zHBXzhaqKXJRMd7KkuWsb4s8zPyakKdijr9E3jgyG8Z

# --- Local overrides (optional) ---
LOCAL_IS_MUTABLE=false
LOCAL_SOL_PAYMENT_VALUE=1
LOCAL_SOL_PAYMENT_DESTINATION=5zHBXzhaqKXJRMd7KkuWsb4s8zPyakKdijr9E3jgyG8Z
LOCAL_UPLOAD_METHOD=
LOCAL_RULE_SET=
LOCAL_MAX_EDITION_SUPPLY=
LOCAL_PINATA_JWT=
LOCAL_PINATA_API_GATEWAY=
LOCAL_PINATA_CONTENT_GATEWAY=
LOCAL_PINATA_PARALLEL_LIMIT=
EOF

echo "✅ Generated $ENV_FILE"
echo "Tip: update PINATA_JWT and KEYPAIR_PATH if needed, then run:  set -a; source $ENV_FILE; set +a"
